name: build

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: production Code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Set up our JDK environment # setup JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - run: npm install
      - run: cd android && ./gradlew assembleRelease
      - run: npm run test
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.KEYPASS }}
          source: "build/"
          target: "/home/thomas/mobile"
